# fly.toml app configuration file generated for bravedesk on 2025-08-09T18:56:46+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bravedesk'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 9999
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
